# default myvault client configuration - using ambassador API gateway
# use the default config.yaml for local tests

grpcAddr: "0.0.0.0:52053"
restAddr: "0.0.0.0:8081"

# secure 0=no TLS, 1=server, 2=mTLS
secure: 0

# generated cert is for localhost

keyFile: "../ssl/server.pem"
certFile: "../ssl/server.crt"
